### ISSUE TITLE
Jar storage location in streamline.yaml should be a shared location in HA mode

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#657] opened 2017-05-25 09:12 UTC
Any topology containing custom jars or udfs or notifiers built on SAM that is running in HA mode will fail if jar storage location is a local FS location. Reason is during registration jar is uploaded to that web server and user should be able to deploy the application from other web server. However, because the jar is uploaded to a location that is local to the node it can run in to issues

**Comment by harshach** [comment] 2017-05-25 15:19
@priyank5485 we can do this via Ambari to ask users to provide HDFS file system for HA. I'll take it up.

**Comment by sureshms** [comment] 2017-06-02 16:51
Duplicate of #687.

**Closed by sureshms** 2017-06-02 16:51 UTC
Labels: bug, P0
