### ISSUE TITLE
Authorizer bugs

### ISSUE THREAD

**Issue by ggolani** [hortonworks/streamline#696] opened 2017-05-30 18:35 UTC
As of build 400,

- Developer role should not be offered to delete service pool
- Admin user cant share application from dev1 to dev2
- if dev1 shared application with dev2, dev2 cant share it further. (by design?)

**Comment by shahsank3t** [comment] 2017-05-31 04:11
@ggolani - Yes, as per the current implementation, if an application is shared to dev2, he cannot share it further. Only dev1 or admin role users will be able to do so.

**Comment by harshach** [comment] 2017-05-31 04:19
@ggolani last point is by design. We only owners or admins to share .

**Comment by arunmahadevan** [comment] 2017-05-31 06:28
> Developer role should not be offered to delete service pool

Developer role currently has only read access to service pool. I will test this.

> Admin user cant share application from dev1 to dev2

This should work from backend. Maybe some UI changes are needed to get it working.

> if dev1 shared application with dev2, dev2 cant share it further. (by design?)

ACLs have a grant flag. If true, the receiver can grant to other users. Right now UI always creates the ACLs with grant=false, so dev2 cannot share further. Enabling this requires UI changes and may be we can do it in a future release.

**Comment by arunmahadevan** [comment] 2017-05-31 07:26
>>Developer role should not be offered to delete service pool

>Developer role currently has only read access to service pool. I will test this.

When a developer tries to delete service pool the following response is returned.

```
DELETE http://localhost:8080/api/v1/catalog/clusters/2

{"responseMessage":"Principal: StreamlinePrincipal{name='bar'} does not have permissions: 
[DELETE] on namespace: cluster id: 2"}
```
But UI displays a wrong message "Cluster is shared with some environment, so it cant be deleted". This needs to be fixed in the UI.

>>Admin user cant share application from dev1 to dev2

>This should work from backend. Maybe some UI changes are needed to get it working.

This works from Authorizer UI but not from the application UI. This should be fixed in the UI.

**Comment by shahsank3t** [comment] 2017-06-01 14:15
Fixed in commit: https://github.com/hortonworks/streamline/commit/d06391802bf5c3ccbb8185cc975422b18db18015

@arunmahadevan Could you please verify with the latest master if everything looks good. Thanks in advance.

**Closed by shahsank3t** 2017-06-01 14:15 UTC
Labels: P0, UI

**Comment by arunmahadevan** [comment] 2017-06-02 06:38
@shahsank3t , verified the following

1. Developer role is not shown delete option unless a service pool is shared with edit access
2. Admin can share App, Env and Service pool created by user1 to user2

**Comment by shahsank3t** [comment] 2017-06-02 06:48
Thanks @arunmahadevan
