### ISSUE TITLE
Streamline artifacts fetching should be configurable via proxy url

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#754] opened 2017-06-22 22:46 UTC
Most users will not have internet access to maven repos in production setup. This will cause issues during the deployment. We should at least allow users to configure proxy url in streamline.yaml such that any artifacts fetching will route through the proxy.
If we are using maven command to do this somewhere , maven already allows one to configure proxy via /home/username/.m2/settings.xml but this doesn't look like working.

**Comment by HeartSaVioR** [comment] 2017-06-24 08:51
Relevant issue : https://issues.apache.org/jira/browse/STORM-2598
Filed issue from Storm side and raised pull requests.
I'll reflect the change to the streamline after PR is merged.

**Comment by HeartSaVioR** [comment] 2017-06-26 05:34
#759

**Closed** 2017-06-27 11:18 UTC
Labels: enhancement, P0

**Comment by ShawnXiao105** [comment] 2017-09-03 23:52
I encountered this problem too, and I have reviewed your Storm (1.0.4) source code and understand you have fixed this problem. but if my current storm is 1.1.0 as HDF default setting. How to solve this problem in my Hortonworks HDF? Upgrade Storm?

**Comment by HeartSaVioR** [comment] 2017-09-04 01:13
@ShawnXiao105 
The fix is not yet published to Apache Storm official release (targeted to Storm 1.2.0), and looks like this patch is also not applied to HDF, unfortunately. Which HDF version do you use?

**Comment by ShawnXiao105** [comment] 2017-09-04 01:19
@HeartSaVioR   3.0.1.0-43. If so, even if I can set proxy setting in Ambari-Streamline config UI, it does not have any effect on Storm usage. Currently now, How can I fix this problem. I cannot deploy applications in My SAM UI now. Please help, Thanks!!

**Comment by ShawnXiao105** [comment] 2017-09-04 01:25
@HeartSaVioR I have tried to use Maven download some certain Jar into Storm user .m2 repository, but it seems that it always wants me to connect central maven repository to resolve dependencies.

**Comment by HeartSaVioR** [comment] 2017-09-04 02:15
@ShawnXiao105 
Are you OK with applying workaround, please check two things below:
1. Please check that there's `.m2` directory in 'storm' user's home directory.
1.a. If it exists, please place artifacts to that directory.
1.b. If it doesn't exist, go to 2.
2. Please check that there's 'local-repo' in either installation of SAM (streamline) or Storm directory.
2.a. If it exists, please place artifacts to that directory.
2.b. Please create `.m2` directory in 'storm' user's home directory, and apply 1.a.

I'll handle the issue in HDF side.

**Comment by ShawnXiao105** [comment] 2017-09-04 02:31
@HeartSaVioR 
Thanks for your reply, I will try your method tomorrow, I am not in office now.
But I have tried the procedures as follows before and please help verify.

1. download maven 3.5.0
2. following [Create a custom process](https://docs.hortonworks.com/HDPDocuments/HDF3/HDF-3.0.1.1/bk_streaming-analytics-manager-user-guide/content/create-custom-processor.html) based on the pom file that Hortonworks support, and change the version to 3.0.1.0-43. Based on the error logs of streamline, I added other artifacts that the logs show such as storm-kafka-client.
3. create a java application and use 'storm' to clean and compile this project to download artifacts into /home/storm/.m2/repository
4. retry to run application is SAM UI

**Comment by ShawnXiao105** [comment] 2017-09-04 02:39
@HeartSaVioR 

I think many more potential users encountered this problem.

https://community.hortonworks.com/questions/118255/streaming-analytics-manager-fail-to-deploy-applica.html

**Comment by ShawnXiao105** [comment] 2017-09-05 06:00
@HeartSaVioR 
I cannot solve it by your method. Please advise.

**Comment by ShawnXiao105** [comment] 2017-09-06 02:27
@HeartSaVioR @harshach 

Maybe the problem is inside storm-submit-tool of hortonworks version

Test in my own PC of official version:

1. download maven
2. download storm 1.1.0 in official link
3. download org.apache.storm:storm-druid:1.1.0.3.0.1.0-43 artifact by maven 
4. test storm-submit-tool
`java -cp storm-submit-tools-1.1.0.jar org.apache.storm.submit.command.DependencyResolverMain "org.apache.storm:storm-druid:1.1.0.3.0.1.0-43"`

The output is as follows:
`DependencyResolver input - artifacts: org.apache.storm:storm-druid:1.1.0.3.0.1.0-43
{"org.apache.storm:storm-druid:jar:1.1.0.3.0.1.0-43":"C:\\Users\\p4370\\.m2\\repository\\org\\apache\\storm\\storm-druid\\1.1.0.3.0.1.0-43\\storm-druid-1.1.0.3.0.1.0-43.jar"}`

It is no problem of storm official 1.1.0 version. And the following is the test procedure of hortonworks storm-submit-tool

1. download storm-submit-tool jar in this [repository](http://nexus-private.hortonworks.com/nexus/content/groups/public/org/apache/storm/storm-submit-tools/1.1.0.3.0.1.0-43/).
2. test the same artifact 
`java -cp storm-submit-tools-1.1.0.3.0.1.0-43.jar org.apache.storm.submit.command.DependencyResolverMain "org.apache.storm:storm-druid:1.1.0.3.0.1.0-43"`

Output result:
`DependencyResolver input - artifacts: org.apache.storm:storm-druid:1.1.0.3.0.1.0-43
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.RuntimeException: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.apache.storm:storm-druid:jar:1.1.0.3.0.1.0-43 in central (http://repo1.maven.org/maven2/)
        at org.apache.storm.submit.command.DependencyResolverMain.main(DependencyResolverMain.java:86)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.apache.storm:storm-druid:jar:1.1.0.3.0.1.0-43 in central (http://repo1.maven.org/maven2/)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:391)
        at org.apache.storm.submit.dependency.DependencyResolver.resolve(DependencyResolver.java:95)
        at org.apache.storm.submit.command.DependencyResolverMain.main(DependencyResolverMain.java:75)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.apache.storm:storm-druid:jar:1.1.0.3.0.1.0-43 in central (http://repo1.maven.org/maven2/)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:373)
        ... 2 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.storm:storm-druid:jar:1.1.0.3.0.1.0-43 in central (http://repo1.maven.org/maven2/)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:39)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:67)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:581)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:249)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)`


Please advise! Thanks

**Comment by HeartSaVioR** [comment] 2017-09-06 05:44
@ShawnXiao105 
OK it looks like a regression. I can reproduce your case, wondering why it works with cached artifacts for maven repo. but doesn't work with hwx repo.

Anyway the commit made regression: https://github.com/apache/storm/commit/2f74ca0282417a781e4672f63b12ab971ea42c39#diff-98554e8f3d282059a6c096450d70e93e

The commit is applied to HDF 3.0 version line and Storm 1.1.1 has same issue as well.

I'll see I can fix it. Thanks for reporting.

**Comment by HeartSaVioR** [comment] 2017-09-06 05:48
@ShawnXiao105 
You need to add the option "hwx-public^http://repo.hortonworks.com/content/groups/public/,hwx-private^http://nexus-private.hortonworks.com/nexus/content/groups/public/" to provide hwx repository even though you are connected to the internet. The thing is, even though we provide these repositories, it ignores cached local artifacts for these repositories.

**Comment by ShawnXiao105** [comment] 2017-09-06 05:59
@HeartSaVioR 

I solved it by a stupid method as follows:
1. edit the build-tool module of storm 1.1.0 and add my own hardcode HTTP proxy parameter
2. recompile and install this module, rename the jar from storm-submit-tools-1.1.0.jar to storm-submit-tools-1.1.0.3.0.1.0-43.jar 
3. replace the jar in /usr/hdf/current/storm/external/storm-submit-tools/
4. **delete http proxy setting in SAM UI Config including httpProxyPassword, httpProxyServer, httpProxyUsername**
5. the storm UI have my application

**Comment by HeartSaVioR** [comment] 2017-09-06 06:32
@ShawnXiao105 
Happy to hear that it works. 

Btw, maven writes where the artifacts come at local repository. The thing is that maven only cares about `repository name` instead of repository url. Here's my observation:

1. I already have storm-hdfs 1.1.0.3.0.0.0-453 in local repo. In its directory, the content of `_remote.repositories` is below: 

```
#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Mon Jul 03 16:57:08 KST 2017
storm-hdfs-1.1.0.3.0.0.0-453.jar>hortonworks.repo=
storm-hdfs-1.1.0.3.0.0.0-453.pom>hortonworks.repo=
```

I turned off the wifi, and ran below command:

> java -cp storm-submit-tools-1.1.1.jar org.apache.storm.submit.command.DependencyResolverMain "org.apache.storm:storm-hdfs:1.1.0.3.0.0.0-453" "hwx-public^http://repo.hortonworks.com/content/groups/public/,hwx-private^http://nexus-private.hortonworks.com/nexus/content/groups/public/"

it **fails** to resolve the artifact.

After that I turned on the wifi to connect the internet, and ran same command again:

> java -cp storm-submit-tools-1.1.1.jar org.apache.storm.submit.command.DependencyResolverMain "org.apache.storm:storm-hdfs:1.1.0.3.0.0.0-453" "hwx-public^http://repo.hortonworks.com/content/groups/public/,hwx-private^http://nexus-private.hortonworks.com/nexus/content/groups/public/"

it **succeeds** to resolve the artifact, and the content of `_remote.repositories` is changed to below: 

```
#NOTE: This is an Aether internal implementation file, its format can be changed without prior notice.
#Wed Sep 06 15:13:47 KST 2017
storm-hdfs-1.1.0.3.0.0.0-453.jar>hortonworks.repo=
storm-hdfs-1.1.0.3.0.0.0-453.pom>hortonworks.repo=
storm-hdfs-1.1.0.3.0.0.0-453.pom>hwx-public=
storm-hdfs-1.1.0.3.0.0.0-453.jar>hwx-public=
```

I turned off the wifi, and ran same command again:

> java -cp storm-submit-tools-1.1.1.jar org.apache.storm.submit.command.DependencyResolverMain "org.apache.storm:storm-hdfs:1.1.0.3.0.0.0-453" "hwx-public^http://repo.hortonworks.com/content/groups/public/,hwx-private^http://nexus-private.hortonworks.com/nexus/content/groups/public/"

yes, it **succeeds** to resolve the artifact.

Important change is introduced via the commit: We should provide necessary repositories except maven default repository **even artifacts are stored to local repository**. 
That's all. **This looks like neither a bug nor a regression.** Repositories should be provided ideally.

This is still just a workaround, and porting proxy feature back to HDF version lines is ongoing.

**Comment by ShawnXiao105** [comment] 2017-09-06 08:35
@HeartSaVioR 

Yes, I have the same observation. 

I don't understand the reason that I have downloaded the artifacts in my m2 repository and why the program still needs to connect the internet to check the dependencies??

Anyway, I wish Hortonworks could solve it shortly as Internet access is not allowed in our DataCenter
