### ISSUE TITLE
Documentation link currently doesn't work.

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/streamline#580] opened 2017-05-18 15:13 UTC
http://streamline.readthedocs.io/en/latest/

returns

```

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \
```

**Comment by shahsank3t** [comment] 2017-07-10 05:26
This is a duplicate of https://github.com/hortonworks/streamline/issues/750
Closing this one to get rid of redundancy.

**Closed by shahsank3t** 2017-07-10 05:26 UTC
Labels: P1
